### ISSUE TITLE
Step 11

### ISSUE THREAD

**Issue by sunnyquiver** [fingolfin/ReleaseTools#10]
Giving the command 

git push master --tags

gives the following error messages: 

fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Should it only be: git push --tags ?

**Comment by fingolfin** [comment]
It should be either `git push --tags`, or `git push origin master --tags`. Both will be equivalent in the "default" setup, but can mean slightly other things if people start using multiple remotes... but these will likely be "advanced" users who don't need those details... So, in short, I guess it should be changed to `git push --tags`, as you suggested.

Thanks, I'll work on this and various other GAP related stuff during the weekend :).

**Comment by fingolfin** [comment]
So much for me working on this over the weekend ... :-( Sorry for the delay, and thanks again for the report.
