### ISSUE TITLE
Rewrite upload code without Pithub

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/ReleaseTools#12]
The upload script right now uses a Perl module "Pithub" for the dirty work. This is a barrier for users, who need to know how to install the Perl module.

Instead, let's use direct HTTP POST calls to do the dirty work -- this can be directly into shell, perl or python, no major external dependencies needed.

E.g. here it is done in shell code (using curl):
https://github.com/gap-packages/NormalizInterface/pull/32

Another option is to implement this in Python 2.7, which also includes a json parser and HTTP upload support. See e.g. https://github.com/dahlia/github-distutils/blob/master/github_distutils.py

Another interesting tool (but written in Go): https://github.com/aktau/github-release

**Comment by sebasguts** [comment]
Python 3 is also possible. But, as I see it, we could also do this via the IO package. I'm currently trying. Maybe this might be the best option, since it does not require anything. (Okay, a compiled IO, but this is fine)

**Comment by fingolfin** [comment]
A compiled io can be a hurdle for some people ;-). But yeah, probably still a lot lower one than installing Pithub (even though it is dead easy with `cpan`, but, well, people don't know about that I guess...)

**Comment by fingolfin** [comment]
But you raise an interesting point. One could convert the whole ReleaseTools to GAP. While this does feel a bit weird for me, it does have a certain appeal. Hrm, need to ponder this.

**Comment by sebasguts** [comment]
Then maybe the best options would be to provide choices: GAP+IO, PitHub, curl. If there is nothing on your computer and you are not able to get any of those, well...

On the second thing: Writing the ReleaseTools completely in GAP would from my point of view something very strange, since you will end up with a lot of lines just stating Exec(...);. Maybe it is the best to leave the shell scripts there, but provide some small GAP Interface, to make it possible to execute the scripts out of GAP. On the other hand, we might get some git interface from GAP out of implementing this purely in GAP, which seems a bit appealing

**Comment by sebasguts** [comment]
It seems like IO does not support https. So this is not an option right now.

**Comment by fingolfin** [comment]
There is now a `release` script does the complete release process; its only dependency is curl (I think...). For this, I borrowed some inspiration and code from @sebasguts release scripts for Homalg and CAP.

This script replaces the `make_dist` and `upload` scripts; I just keep them around for existing users (and also because the README is not yet updated ;-).

@sebasguts I know that you have some different needs for Homalg and CAP, but I would still be interested in aligning our two scripts; the more similar they are, the easier it becomes to share improvements. Perhaps we can refactor both of our scripts to make this easier? Let's talk about this in St Andrews?!

**Comment by sebasguts** [comment]
The script seems very nice, I think I will include some of the things in the homalg/CAP dist scripts. And I think the idea of aligning them even more seems like a good project for St. Andrews.
