### ISSUE TITLE
Should a link to PackageInfo.g file be visible from the package website?

### ISSUE THREAD

**Issue by alex-konovalov** [fingolfin/ReleaseTools#15]
Many GAP packages include a link to their PackageInfo.g file on their homepage (as a random example, see e.g. http://cmup.fc.up.pt/cmup/mdelgado/automata/).

This file is quite technical, and its stand-alone copy is needed to check whether package updates are available. Thus, it's not really necessary to make this link visible on the package website, as soon as the link itself it working and is specified in https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList. 

However, while the only detail needed to add the package for the redistribution is the URL of the PackageInfo.g file, in the majority of cases the authors contact us with the URL of the package website. If the link to PackageInfo.g is not there, one should ask the authors in order to figure it out. Therefore, having such link included in the template and being automatically updated by the package release scripts may be helpful.

**Comment by fingolfin** [comment]
This is already possible, nothing needs to be changed in the ReleaseTools for this -- rather, the package authors would need to adapt the package template they use.... Of course we could modify the template at https://github.com/fingolfin/GitHubPagesForGAP to show that link by default -- perhaps open a new issue there with that suggestion?

**Comment by alex-konovalov** [comment]
@fingolfin Thanks - it happened that I've already submitted it there last year :) https://github.com/fingolfin/GitHubPagesForGAP/issues/3
