### ISSUE TITLE
Hack for getting info from package info does not work ...

### ISSUE THREAD

**Issue by sebasguts** [fingolfin/ReleaseTools#25]
... on my computer. Every line that should be evaluated has a trailing `\r`, so the variables are not set properly. Here is a minimal example script:
```
eval $(gap -A -q -b <<EOF
Print("echo $PWD");
QUIT;
EOF
)
```
which, when executed, gives the following error:
```
./test_eval.sh: Zeile 5: $'\recho': Kommando nicht gefunden.
```

**Comment by fingolfin** [comment]
This seems to be caused by gap-system/gap#430

But you are affected only because your `gap` command does not honor the `-A` flag... *cough*

**Comment by fingolfin** [comment]
I added a workaround for this some time ago.
