### ISSUE TITLE
function keyword in sh (POSIX)

### ISSUE THREAD

**Issue by csoeger** [fingolfin/ReleaseTools#27]
I had a issue while preparing a release on NormalizInterface. Everything works fine until:
```
Validating PackageInfo.g...
../ReleaseTools/release: 339: ../ReleaseTools/release: function: not found
```
That line refers to the line `function jsonval {`.

The script uses `/bin/sh`, on my system (Ubuntu 15.10) it is a symlink to `dash` which does not understand the `function` keyword. Changing the shell to `bash` it did work.

From
http://unix.stackexchange.com/questions/73750/difference-between-function-foo-and-foo
I understood that the best solution would be to just remove the `function `.

**Comment by fingolfin** [comment]
So, does removing the "function" keyword actually fix the issue for you?

**Comment by csoeger** [comment]
Just tested it, I also had to add `()`. Created a pull request.
