### ISSUE TITLE
Portability problems

### ISSUE THREAD

**Issue by markuspf** [fingolfin/ReleaseTools#35]
The `release` script seems to have a couple of portability problems. Here are the ones I have identified so far (using DragonFly BSD).

 * I can only reliably get the script to run using `bash`, neither `zsh` nor `/bin/sh` work. One of the issues is obviously the `read -d` feature that is used, but that's supported by zsh. It seems that zsh does not like `for i in $ARCHIVE_FORMATS`.
 * The script seems to be assuming gnu-ish sed/awk, because the parsing of json fails in jsonval, replacing sed/awk with gsed/gawk "solves" the problem for me.

**Comment by fingolfin** [comment]
This should be fixed now. I tried with bash, dash and zsh -- note that zsh *is* compatible when run in "sh emulation mode", e.g. if it is installed as system shell `/bin/sh`. If you run the `release` script directly via `zsh release`, that won't quite work.

**Comment by fingolfin** [comment]
And yeah, all of this would be avoided if the whole thing was written completly in python... I am tempted to do that, but of course such a rewrite will loose all the testing efforst I already put into this, and would take some time to stabilize again. I am certainly interested, but for now, it was more efficient for me to just adapt the existing shell script.

**Comment by fingolfin** [comment]
@markuspf Can you confirm whether it works now for you?

**Comment by fingolfin** [comment]
Since I heard nothing again, I'll assume this is resolved. If not, feel free to reopen.
