### ISSUE TITLE
sh regular expression capability

### ISSUE THREAD

**Issue by csoeger** [fingolfin/ReleaseTools#37]
My `sh` does not understand the wildcard expression on line 514

`cp "$TMP_DIR/$BASENAME/doc"/*.{css,html,js,txt} doc/`

leading to the error

`cp: cannot stat ‘/home/csoeger/gap/pkg/NormalizInterface/tmp/NormalizInterface-0.9.8/doc/*.{css,html,js,txt}’: No such file or directory`

It does work with bash. I'm using Ubuntu 15.10.

**Comment by fingolfin** [comment]
Ouch. Thanks for the report, will fix.

Yet another reason to rewrite this whole tool in python to increase portability...
