### ISSUE TITLE
Renaming README is not picked up

### ISSUE THREAD

**Issue by alex-konovalov** [fingolfin/ReleaseTools#39]
I have renamed README to README.md but this has not been picked up automatically. I had to fix this with https://github.com/gap-packages/example/commit/71054c6f6cb45f5d2961f781ae2f48970f934013 and I am not sure that's the right way of fixing this. I've tried to run `update.g` but to no avail.

**Comment by fingolfin** [comment]
This is really more an issue in https://github.com/fingolfin/GitHubPagesForGAP

**Comment by fingolfin** [comment]
Fixed now, see https://github.com/fingolfin/GitHubPagesForGAP/commit/83c29de49be48e382c135dd42baf6ae37f3c6881
