### ISSUE TITLE
`git diff-index` occasionally fails

### ISSUE THREAD

**Issue by ChrisJefferson** [fingolfin/ReleaseTools#43]
The line:

```
git diff-index --quiet HEAD -- ||
    error "uncommitted changes detected 2"
```

Occasionally fails on mac. The problem seems very sensitive -- doing a `git status` or a `sleep 1` just before seems to fix the problem.

**Comment by ChrisJefferson** [comment]
`git update-index --refresh --` before running `git diff-index` seems to clear up the problem reliably.

**Comment by alex-konovalov** [comment]
After the fix, I am having an error:
```
error: --refresh: does not exist and --remove not passed
fatal: Unable to process path --refresh
```

**Comment by fingolfin** [comment]
Fixed the fix.
@alex-konovalov next time, please submit a new issue. I only saw this comment on a closed issue by pure chance
